### ISSUE TITLE
When page is rendering the control does not render....

### ISSUE THREAD

**Issue by Charmatzis** [LiveBy/react-leaflet-control#1]
I have insert a new control in the <Map> element like this ...
`<Control position="topleft">
            <div>
              <div>
                <input type="button" title="Add overlay image" className="button-addimage" onClick={this.addImageOverlay}/>
              </div>
</div>
</Control>`
When I start the page for the first time the control does not render. When I do a small change in the code the control appears when the page is refreshing. Why is that?

**Comment by Charmatzis** [comment]
I search a little bit and I believe it is when it renders for the first time it return null, but if it is updated it calls the renderContent method which renders the component as it is.

**Comment by jgimbel** [comment]
Indeed. This needs to update in a `componentDidMount` function. I will update in a hour or so.

**Comment by jgimbel** [comment]
[This commit](https://github.com/LiveBy/react-leaflet-control/commit/b9a6886260cb6b0eb4094b6d148d6e1896b91510) resolved this issue for me. Let me know when you have confirmed.

**Comment by Charmatzis** [comment]
Yeap, problem solved. THX!!!!

**Comment by aalpgiray** [comment]
Hi, I know this is closed. But I am on version 2.0.0 and experiencing the same issue. It loads after only it hot reloads.
