### ISSUE TITLE
IE10 Support

### ISSUE THREAD

**Issue by ghostd** [LiveBy/react-leaflet-control#10]
Hi,

Your code works great. If you add the following lines, it will work with IE10:
```
export default class CustomControl extends MapControl {
  // for IE9 & IE10 support
  static contextTypes = MapControl.contextTypes;
  static childContextTypes = MapControl.childContextTypes;
```

I found this workaround here:
https://github.com/PaulLeCam/react-leaflet/pull/235

Regards

**Comment by jgimbel** [comment]
Pushed to master, I will release after I have had a chance to test it.
