### ISSUE TITLE
Creating a custom zoom 

### ISSUE THREAD

**Issue by jamunoz** [LiveBy/react-leaflet-control#3]
Hello Joel!

Sorry for post it here but... Do you have an example how to create a zoom button (either doing zoom in or out) using the library?
I've tried to follow the example shown but without success.

PD. In the example if I rename "bounds" var for "center" in onClick event, It works.

**Comment by jgimbel** [comment]
I responded to this [stackoverflow](http://stackoverflow.com/questions/38547540/having-trouble-getting-a-custom-zoom-button-in-react-leaflet/38553253#38553253) question. Is it yours?

**Comment by jamunoz** [comment]
Yes, It's me. I replied to you. Regards!

**Comment by jgimbel** [comment]
Are we done here?

**Comment by jamunoz** [comment]
Yes! I'm really thankful for you answer!
