### ISSUE TITLE
Could not find declaration file in module 'react-leaflet-contorl'

### ISSUE THREAD

**Issue by codenamenikky** [LiveBy/react-leaflet-control#33]
Hi, thanks for working on the package. I am trying to implement a simple drop down for one of my maps. I can't get the module to work. Below is my configuration. I get a prompt on the VS code telling me it couldn't find declaration file for the module. I am not sure if those are related. I tried to copy paste the readme example and couldn't get it to display. Even after changing a few things to solve some render errors. 

```
    "leaflet": "^1.4.0",
    "react": "^16.7.0",
    "react-delay": "^0.1.0",
    "react-dom": "^16.7.0",
    "react-firebaseui": "^3.1.2",
    "react-leaflet": "^2.2.0",
    "react-leaflet-control": "^2.1.0",
```

**Comment by jgimbel** [comment]
Version 2.1.1 should fix this error.

**Comment by codenamenikky** [comment]
thanks for the update, I could get at least a button to show on the map so i might use it to just control the rest of the layout around the map. I still couldn't get a dropdown list to work but i think I have something to work with now.
