### ISSUE TITLE
Legacy API

### ISSUE THREAD

**Issue by mbrucher** [LiveBy/react-leaflet-control#34]
It seems that componentDidMount is deprecated and may be removed in React 17.
Any plan on changing this?
I suppose maybe with a layer like redux it might not be required?

**Comment by limfinity** [comment]
Hey @mbrucher! :) Where did you get that from? AFAIK there is currently no timetable for removing `componentDidMount`. Adding redux here would introduce a very unnecessary third party dependency in my opinion.
Actually I think the contrary is the case. `componentDidMount` was strengthened while other lifecycle methods were deprecated.
> Move code with side effects to componentDidMount, and set initial state in the constructor.
