### ISSUE TITLE
Removing a Control breaks Leaflet zooming and panning

### ISSUE THREAD

**Issue by lediur** [LiveBy/react-leaflet-control#4]
Running Leaflet 1.0.0 rc3 and React-Leaflet 1.0.0 beta 3, occurs in both Microsoft Edge and Chrome.

**Description**
If I add, then remove a Control component from a Map component, the Map no longer responds to zoom or panning, and features on top of the map render extremely weirdly. No errors are logged to console.

**Cause**:
I narrowed this down to the `onRemove` function in `Control.Dumb.js`. I think `onRemove` doesn't remove events for the Control component properly, so it breaks all events on the Map component.

**Workaround:**
Removing `onRemove` entirely fixes the bug (i.e. I can add and remove as many Controls as I want without problems).

Could this be a result of a change in Leaflet 1.0 that isn't changed in `onRemove`?

**Comment by lediur** [comment]
Adding a check around the call to `map.off` also works as a workaround:

``` js
if (this.options.onOff) {
    map.off(this.options.onOff, this.options.handleOff, this);
}
```

**Comment by jgimbel** [comment]
I will not be able to fix this until tomorrow night. You are welcome to make a pull request with the changes described

**Comment by lediur** [comment]
Done - thanks!
