### ISSUE TITLE
Control Rendering underneath Map Tile layer on iOS only

### ISSUE THREAD

**Issue by brucem1976** [LiveBy/react-leaflet-control#42]
I've got a Map coming up on a Modal that renders fullscreen, and so I have a control that renders top right to close the Modal. On PC and Android, this renders correctly, but on iOS the control is not visible there - however when I drag the map down and left I can see the Control there, under the tile that I've just moved out the way. Strangely, when I press on the location where the control should be (even though it is under the tile) the onClick action still executes.

**Comment by jayala** [comment]
Had this problem with Ionic when rendering the map inside an IonContent. For what it's worth now..
