### ISSUE TITLE
React-Leaflet v3 compatibility

### ISSUE THREAD

**Issue by paambaati** [LiveBy/react-leaflet-control#44]
The component doesn't work with the latest version of React-Leaflet. [v3 of React-Leaflet is a complete rewrite](https://github.com/PaulLeCam/react-leaflet/releases/tag/v3.0.0) that contains breaking changes.

**Comment by paambaati** [comment]
I was able to implement a custom control on React-Leaflet v3 like this —

```tsx
import type { DetailedHTMLProps, HTMLAttributes, ReactNode } from 'react';

/**
 * @see https://react-leaflet.js.org/docs/example-react-control
 */

// Classes used by Leaflet to position controls.
const POSITION_CLASSES = {
    bottomleft: 'leaflet-bottom leaflet-left',
    bottomright: 'leaflet-bottom leaflet-right',
    topleft: 'leaflet-top leaflet-left',
    topright: 'leaflet-top leaflet-right',
} as const;

const MapCustomControl = (props: MapCustomControlProps): JSX.Element => {
    const { position, containerProps, children } = props;
    return (
        <div className={POSITION_CLASSES[position]}>
            <div className='leaflet-control leaflet-bar' {...containerProps}>
                {children}
            </div>
        </div>
    );
};

export type MapCustomControlProps = {
    position: keyof typeof POSITION_CLASSES;
    containerProps?: DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>;
    children: ReactNode;
};

MapCustomControl.defaultProps = {
    position: 'topleft' as MapCustomControlProps['position'],
    containerProps: {},
    children: null,
};

export default MapCustomControl;
```

You can then simply use this as a child of [`MapContainer`](https://react-leaflet.js.org/docs/api-map#mapcontainer).

**Comment by podsevalovAlex** [comment]
Very useful, thanks.

**Comment by EliteMasterEric** [comment]
This has the issue of not actually putting the control into the control container, and for me that caused the controls to overlap each other.

EDIT: It also has an issue where click on the control sends a click event to the map behind it.

**Comment by szkkteam** [comment]
My solution for the custom control which using react-leaflet v3 hooks
```javascript
import React, {
    Ref,
    forwardRef,
    useEffect,
  } from 'react'
import { createPortal } from 'react-dom'
import { createElementHook, createControlHook } from '@react-leaflet/core'
import { Control, DomUtil, DomEvent } from 'leaflet'

const DumbControl = Control.extend({
    options: {
        className: "",
        onOff: "",
        handleOff: function noop() {}
      },

    onAdd(/* map */) {
        var _controlDiv = DomUtil.create("div", this.options.className);
        DomEvent.disableClickPropagation(_controlDiv);
        return _controlDiv;
    },
    
    onRemove(map) {
        if (this.options.onOff) {
          map.off(this.options.onOff, this.options.handleOff, this);
        }
    
        return this;
    }
})

const createControl = (props, context) => {
    const instance = new DumbControl(props)    
    return { instance, context: { ...context, overlayContainer: instance } }

}

const useControlElement = createElementHook(createControl)
const useControl = createControlHook(useControlElement)


//create your forceUpdate hook
const useForceUpdate () => {
    const [value, setValue] = useState(0); // integer state
    return () => setValue(value => value + 1); // update the state to force render
}


const createLeafletControl = (useElement) => {
    const Component = (props, ref) => {
        const forceUpdate = useForceUpdate();
        const { instance } = useElement(props).current

        useEffect(() => {
            // Origin: https://github.com/LiveBy/react-leaflet-control/blob/master/lib/control.jsx
            // This is needed because the control is only attached to the map in
            // MapControl's componentDidMount, so the container is not available
            // until this is called. We need to now force a render so that the
            // portal and children are actually rendered.
            forceUpdate()
        }, [])

        const contentNode = instance.getContainer()
        return contentNode ? createPortal(props.children, contentNode) : null
    }
    return forwardRef(Component)
}


export default createLeafletControl(useControl)
```

**Comment by AndrejGajdos** [comment]
+1 would be nice if this library was compatible with react-leaflet v3

**Comment by mylastore** [comment]
> ```js
> useControl
> ```

Do you mind sharing an example on how to use it?

**Comment by podsevalovAlex** [comment]
Place this component into MapContainer
```
import { useState } from 'react'
import { useMapEvents } from 'react-leaflet'
import Fab from '@material-ui/core/Fab'
import AddIcon from '@material-ui/icons/Add'
import { Typography } from '@material-ui/core'

const MapInfo = () => {
  const [position, setPosition] = useState(null)

  const map = useMapEvents({
    mousemove(e) {
      setPosition(e.latlng)
    },
    mouseout(e) {
      // code to stop process
    },
  })
  return position === null ? null : (
    <div className="leaflet-top leaflet-right">
      <div className="leaflet-control">
        <Fab variant="extended" size="medium" color="primary">
          <AddIcon />
          <Typography variant="body2" noWrap>
            {position.lng.toFixed(4)} , {position.lat.toFixed(4)}
          </Typography>{' '}
        </Fab>
      </div>
    </div>
  )
}

export default MapInfo
```

**Comment by Lorthiz** [comment]
> > ```js
> > useControl
> > ```
> 
> Do you mind sharing an example on how to use it?


@mylastore I was able to just copy whole code and paste it to separate file named 'UseControl.tsx' in my hooks folder. There were some problems for me since I am using Typescriptp but after throwing few  ': any' and changing functions to arrow ones everything was all right. Now I can just import it as any other hook: 

`import UseControl from "../../../hooks/UseControl";`

And wrap it around my own code

```
        <UseControl>
            <button onClick={() => console.log('IT WORKS!')}>SomeButton</button>
        </UseControl>
```

You can also change position of your control by simply passing one of four positions to that hook:

```
        <UseControl position='bottomleft'>
            <button onClick={() => console.log('IT WORKS!')}>SomeButton</button>
        </UseControl>
```

and directions are: `bottomleft`, `bottomright`, `topright` and `topleft`. If you pass the wrong position you will get an error

How does it work? I have no idea :D

**Comment by glockwoo** [comment]
### For beginners
I'm very new to Javascript and still find it confusing after using more structured languages for a long time. @szzkteam's code above has worked for me (very clever, thank you) but my environment (vsc/yarn on FreeBSD v13) insisted on having useForceUpdate as an arrow function and I had to add useState to my imports. Both easy and obvious points to anyone with more experience I'm sure, but I post this for others who, like me, are just feeling their way in the dark.

**Comment by firflant** [comment]
This package does a very similar thing and works under react-leaflet v3:
https://www.npmjs.com/package/react-leaflet-custom-control

**Comment by charlieforward9** [comment]
From https://github.com/PaulLeCam/react-leaflet/issues/866

> This worked to stop click/drag events from propagating through to the map:
> ```
> const MyControl = () => {
>   const ref = useRef<HTMLDivElement>(null);
> 
>     useEffect(() => {
>         if (ref.current) {
>             L.DomEvent.disableClickPropagation(ref.current);
>         }
>     });
> 
>   return (
>     <div ref={ref}>
>        ... YOUR JSX
>     </div>
>   )
> };
> ```

This blocks the usage of [ReactSlider](https://github.com/zillow/react-slider) in the control component.
